server:
  port: 8081

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: Personal-Blog-Website
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_blog_website?useSSL=false&serverTimezone=UTC&allowMultiQueries=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 192.168.16.128
    port: 6380
  mail:
    host: smtp.qq.com
    port: 587
    username: 3467884929@qq.com
    password: ksexqkqbifbjdcaa
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 网站配置
xixi:
  website:
    title: 神になる代償は何ですか？
    home: https://xixi.cc
    admin: https://admin.xixi.cc
    cv: https://xixi.cc/cv
    blog: https://xixi.cc/blog
  email:
    personal: xixi
    from: 3467884929@qq.com
  jwt:
    secret-key: "BOYBOYBOYBOYBOYBOYBOYBOYBOYBOYBOYBOYBOYBEE"
    ttl: 1440
    token-name: Authorization
  alioss:
    endpoint: ${ALI_OSS_ENDPOINT}
    access-key-id: ${ALI_OSS_ACCESS_KEY_ID}
    access-key-secret: ${ALI_OSS_ACCESS_KEY_SECRET}
#高德地图key
amap:
  api:
    key: d11d678317c461e4b0bd978ac962dea7
    url: https://restapi.amap.com/v5/ip
# 开启 MyBatis SQL 日志
logging:
  level:
    com.xixizai.personalblogwebsite.mapper: debug
    com.github.pagehelper: debug


# PageHelper 配置
pagehelper:
  reasonable: false
  support-methods-arguments: true

